language: python
python:
    - "3.6.1"
before_install:
    - pip install matplotlib
    - pip install scipy
    - pip install pytest pytest-cov
    - pip install coveralls
env:
    - MPLBACKEND="agg"
install:
    - pip install -e .
script:
    - pytest --cov=src --ignore=src/bin --ignore=examples
after_success:
    - coveralls
