language: python
python:
    - "3.6.1"
before_install:
    - pip install scipy
    - pip install pytest pytest-cov
    - pip install coveralls
install:
    - pip install -e .
script:
    - pytest --cov=src --ignore=src/bin
after_success:
    - coveralls
